CRESP substepping
piernik-dev/piernik pull request #440
Opened 2021-04-20 10:55 UTC by mogrodnik

Can speed up experiments utilizing CRESP where spectral timesteps are much shorter than timesteps for fluid components.
Allows substepping in spectrum update: state of each cell is separately updated in a loop of n_substeps by dt_substep=dt / n_substeps, allowing to ignore spectral timestep when choosing shortest for global domain update.

2021-04-20 11:15 UTC, mogrodnik commented
Check & comment this please

2021-04-20 21:51 UTC, gawrysz requested changes
Please merge at least 4654ade84d01da5dd871edef351220efe96ba78f.

I'm not sure whether problems pointed out in 4c65696f80291d9a2310d4965a330da668dfe49b are related to this particular branch or not. Perhaps these can be fixed up separately.

2021-04-23 08:54 UTC, gawrysz approved these changes

2021-04-23 09:00 UTC, gawrysz approved these changes

2021-04-26 08:53 UTC, woolt approved these changes

2021-04-26 09:11 UTC, merged