Fix SIGSEGV in initproblem for mcrtest_cresp
piernik-dev/piernik pull request #477
Opened 2022-01-14 17:35 UTC by mogrodnik

In mcrtest_cresp test problem, when setting ncre = 0, the module is switched off and is not being initialized. In mcrtest_cresp problem file, initproblem.F90, a check for 'use_cresp' was overlooked which resulted in segmentation fault. This is fixed by importing 'use_cresp' and checking it during initialization.

2022-01-14 22:13 UTC, gawrysz approved these changes

2022-01-14 22:52 UTC, gawrysz requested changes
There are also invalid HDF requests in `save_smap_to_open` in the `cresp_io` file.

2022-01-16 19:55 UTC, gawrysz approved these changes

2022-01-16 20:00 UTC, gawrysz approved these changes

2022-01-17 11:20 UTC, woolt approved these changes

2022-01-17 11:41 UTC, merged